const validPrograms = [
    'BSc Agriculture',
    'BSc Agricultural Biotechnology',
    'BSc Agribusiness Management',
    'BSc Landscape Design and Management',
    'BSc Natural Resources Management',
    'BSc Forest Resources Technology',
    'BSc Aquaculture and Water Resources Management',
    'BSc Packaging Technology',
    'BSc Architecture',
    'BSc Construction Technology and Management',
    'BSc Quantity Surveying and Construction Economics',
    'BSc Development Planning',
    'BSc Human Settlement Planning',
    'BSc Land Economy',
    'BSc Real Estate',
    'BFA Fine Art and Curatorial Practice',
    'BA Communication Design',
    'BA Integrated Rural Art and Industry',
    'BA Publishing Studies',
    'BSc Metal Product Design Technology',
    'BSc Textile Design and Technology',
    'BSc Fashion Design',
    'BSc Ceramics Technology',
    'BEd Junior High School Education',
    'BSc Aerospace Engineering',
    'BSc Agricultural Engineering',
    'BSc Automobile Engineering',
    'BSc Biomedical Engineering',
    'BSc Chemical Engineering',
    'BSc Civil Engineering',
    'BSc Computer Engineering',
    'BSc Electrical/Electronic Engineering',
    'BSc Geological Engineering',
    'BSc Geomatic Engineering',
    'BSc Industrial Engineering',
    'BSc Marine Engineering',
    'BSc Materials Engineering',
    'BSc Mechanical Engineering',
    'BSc Metallurgical Engineering',
    'BSc Petrochemical Engineering',
    'BSc Petroleum Engineering',
    'BSc Telecommunication Engineering',
    'BDS Bachelor of Dental Surgery (Fee-Paying Only)',
    'DVM Doctor of Veterinary Medicine',
    'BSc Disability and Rehabilitation Studies',
    'BHM Bachelor of Herbal Medicine',
    'BSc Human Biology (Medicine)',
    'BSc Medical Laboratory Sciences',
    'BSc Medical Imaging',
    'BSc Midwifery',
    'BSc Nursing',
    'BSc Physiotherapy and Sports Science',
    'PharmD Doctor of Pharmacy',
    'BA Akan Language and Culture',
    'BA Economics',
    'BA English',
    'BA French and Francophone Studies',
    'BA Geography and Rural Development',
    'BA History',
    'BA Linguistics',
    'BA Media and Communication Studies',
    'BA Political Studies',
    'BA Religion and Human Development',
    'BA Sociology',
    'BA Social Work',
    'BSc Business Administration (Human Resource Management/Management)',
    'BSc Business Administration (Marketing/International Business)',
    'BSc Business Administration (Accounting/Banking and Finance)',
    'BSc Business Administration (Logistics and Supply Chain Management/Business Information Technology)',
    'BSc Hospitality and Tourism Management',
    'LLB',
    'BSc Biochemistry',
    'BSc Food Science and Technology',
    'BSc Biological Sciences',
    'BSc Environmental Sciences',
    'BSc Chemistry',
    'BSc Computer Science',
    'BSc Mathematics',
    'BSc Actuarial Science',
    'BSc Statistics',
    'BSc Physics',
    'BSc Meteorology and Climate Science',
    'Doctor of Optometry',
    'BSc Civil Engineering (Obuasi Campus)',
    'BSc Electrical/Electronic Engineering (Obuasi Campus)',
    'BSc Geological Engineering (Obuasi Campus)',
    'BSc Geomatic Engineering (Obuasi Campus)',
    'BSc Materials Engineering (Obuasi Campus)',
    'BSc Mechanical Engineering (Obuasi Campus)',
    'BSc Metallurgical Engineering (Obuasi Campus)',
    'BSc Medical Laboratory Sciences (Obuasi Campus)',
    'BSc Midwifery (Obuasi Campus)',
    'BSc Nursing (Obuasi Campus)',
    'BBA (HRM/Management) (Obuasi Campus)',
    'BBA (Marketing/International Business) (Obuasi Campus)',
    'BBA (Accounting/Banking and Finance) (Obuasi Campus)',
    'BBA (Logistics & Supply Chain Management/Business Information Technology) (Obuasi Campus)',
    'BSc Environmental Sciences (Obuasi Campus)'
  ];
  
  const cutOffAggregates = {
    'BSc Agriculture': 20,
    'BSc Agricultural Biotechnology': 17,
    'BSc Agribusiness Management': 15,
    'BSc Landscape Design and Management': 17,
    'BSc Natural Resources Management': 18,
    'BSc Forest Resources Technology': 24,
    'BSc Aquaculture and Water Resources Management': 20,
    'BSc Packaging Technology': 15,
    'BSc Architecture': 7,
    'BSc Construction Technology and Management': 9,
    'BSc Quantity Surveying and Construction Economics': 9,
    'BSc Development Planning': 9,
    'BSc Human Settlement Planning': 10,
    'BSc Land Economy': 8,
    'BSc Real Estate': 9,
    'BFA Fine Art and Curatorial Practice': 16,
    'BA Communication Design': 11,
    'BA Integrated Rural Art and Industry': 15,
    'BA Publishing Studies': 12,
    'BSc Metal Product Design Technology': 16,
    'BSc Textile Design and Technology': 13,
    'BSc Fashion Design': 11,
    'BSc Ceramics Technology': 23,
    'BEd Junior High School Education': 15,
    'BSc Aerospace Engineering': 7,
    'BSc Agricultural Engineering': 13,
    'BSc Automobile Engineering': 10,
    'BSc Biomedical Engineering': 7,
    'BSc Chemical Engineering': 7,
    'BSc Civil Engineering': 7,
    'BSc Computer Engineering': 6,
    'BSc Electrical/Electronic Engineering': 6,
    'BSc Geological Engineering': 8,
    'BSc Geomatic Engineering': 9,
    'BSc Industrial Engineering': 10,
    'BSc Marine Engineering': 9,
    'BSc Materials Engineering': 10,
    'BSc Mechanical Engineering': 7,
    'BSc Metallurgical Engineering': 11,
    'BSc Petrochemical Engineering': 7,
    'BSc Petroleum Engineering': 6,
    'BSc Telecommunication Engineering': 9,
    'BDS Bachelor of Dental Surgery (Fee-Paying Only)': 6,
    'DVM Doctor of Veterinary Medicine': 10,
    'BSc Disability and Rehabilitation Studies': 13,
    'BHM Bachelor of Herbal Medicine': 14,
    'BSc Human Biology (Medicine)': 6,
    'BSc Medical Laboratory Sciences': 7,
    'BSc Medical Imaging': 7,
    'BSc Midwifery': 8,
    'BSc Nursing': 7,
    'BSc Physiotherapy and Sports Science': 12,
    'PharmD Doctor of Pharmacy': 6,
    'BA Akan Language and Culture': 15,
    'BA Economics': 10,
    'BA English': 13,
    'BA French and Francophone Studies': 14,
    'BA Geography and Rural Development': 10,
    'BA History': 15,
    'BA Linguistics': 15,
    'BA Media and Communication Studies': 9,
    'BA Political Studies': 9,
    'BA Religion and Human Development': 20,
    'BA Sociology': 11,
    'BA Social Work': 11,
    'BSc Business Administration (Human Resource Management/Management)': 7,
    'BSc Business Administration (Marketing/International Business)': 9,
    'BSc Business Administration (Accounting/Banking and Finance)': 7,
    'BSc Business Administration (Logistics and Supply Chain Management/Business Information Technology)': 8,
    'BSc Hospitality and Tourism Management': 10,
    'LLB': 6,
    'BSc Biochemistry': 9,
    'BSc Food Science and Technology': 11,
    'BSc Biological Sciences': 9,
    'BSc Environmental Sciences': 12,
    'BSc Chemistry': 15,
    'BSc Computer Science': 7,
    'BSc Mathematics': 15,
    'BSc Actuarial Science': 10,
    'BSc Statistics': 12,
    'BSc Physics': 16,
    'BSc Meteorology and Climate Science': 17,
    'Doctor of Optometry': 6,
    'BSc Civil Engineering (Obuasi Campus)': 11,
    'BSc Electrical/Electronic Engineering (Obuasi Campus)': 10,
    'BSc Geological Engineering (Obuasi Campus)': 14,
    'BSc Geomatic Engineering (Obuasi Campus)': 15,
    'BSc Materials Engineering (Obuasi Campus)': 15,
    'BSc Mechanical Engineering (Obuasi Campus)': 12,
    'BSc Metallurgical Engineering (Obuasi Campus)': 16,
    'BSc Medical Laboratory Sciences (Obuasi Campus)': 9,
    'BSc Midwifery (Obuasi Campus)': 13,
    'BSc Nursing (Obuasi Campus)': 12,
    'BBA (HRM/Management) (Obuasi Campus)': 15,
    'BBA (Marketing/International Business) (Obuasi Campus)': 16,
    'BBA (Accounting/Banking and Finance) (Obuasi Campus)': 12,
    'BBA (Logistics & Supply Chain Management/Business Information Technology) (Obuasi Campus)': 15,
    'BSc Environmental Sciences (Obuasi Campus)': 19
  };
  
  const collegeFees = {
    'College of Agriculture and Natural Resources': {
      regular_freshers: 2748.30,
      fee_paying_freshers: 6937.45,
      residential_freshers: 2167.80
    },
    'College of Art and Built Environment': {
      regular_freshers: 2748.30,
      fee_paying_freshers: 6937.45,
      residential_freshers: 2167.80
    },
    'College of Engineering': {
      regular_freshers: 3777.55,
      fee_paying_freshers: 9396.70,
      residential_freshers: 2167.80
    },
    'College of Health Sciences': {
      regular_freshers: 3777.55,
      fee_paying_freshers: 9396.70,
      residential_freshers: 2167.80
    },
    'College of Humanities and Social Sciences': {
      regular_freshers: 2307.95,
      fee_paying_freshers: 6497.10,
      residential_freshers: 2167.80
    },
    'College of Science': {
      regular_freshers: 2748.30,
      fee_paying_freshers: 6937.45,
      residential_freshers: 2167.80
    },
    'Obuasi Campus': {
      regular_freshers: 2748.30,
      fee_paying_freshers: 6937.45,
      residential_freshers: 2167.80
    }
  };
  
  const electiveRequirements = {
    'BSc Agriculture': ['Chemistry', 'Physics', 'Biology', 'General Agriculture', 'Animal Husbandry', 'Crop Husbandry', 'Horticulture'],
    'BSc Agricultural Biotechnology': ['Chemistry', 'Physics', 'Biology', 'General Agriculture'],
    'BSc Agribusiness Management': ['Chemistry', 'Physics', 'Biology', 'General Agriculture', 'Economics', 'Geography', 'Business Management'],
    'BSc Landscape Design and Management': ['Chemistry', 'Physics', 'Biology', 'General Agriculture', 'Geography'],
    'BSc Natural Resources Management': ['Chemistry', 'Physics', 'Biology', 'General Agriculture', 'Forestry'],
    'BSc Forest Resources Technology': ['Chemistry', 'Physics', 'Biology', 'General Agriculture', 'Forestry'],
    'BSc Aquaculture and Water Resources Management': ['Chemistry', 'Physics', 'Biology', 'General Agriculture'],
    'BSc Packaging Technology': ['Chemistry', 'Physics', 'Mathematics'],
    'BSc Architecture': ['Physics', 'Mathematics', ['Chemistry', 'Geography', 'Technical Drawing', 'Visual Art']],
    'BSc Construction Technology and Management': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing', 'Building Construction']],
    'BSc Quantity Surveying and Construction Economics': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing', 'Economics']],
    'BSc Development Planning': ['Geography', 'Economics', ['Government', 'Mathematics']],
    'BSc Human Settlement Planning': ['Geography', 'Economics', ['Government', 'Mathematics']],
    'BSc Land Economy': ['Geography', 'Economics', ['Government', 'Mathematics']],
    'BSc Real Estate': ['Geography', 'Economics', ['Government', 'Mathematics']],
    'BFA Fine Art and Curatorial Practice': ['General Knowledge in Art', ['Picture Making', 'Sculpture', 'Graphic Design']],
    'BA Communication Design': ['General Knowledge in Art', ['Graphic Design', 'Picture Making']],
    'BA Integrated Rural Art and Industry': ['General Knowledge in Art', ['Basketry', 'Leatherwork', 'Ceramics']],
    'BA Publishing Studies': ['English Literature', 'Government', 'History', 'Economics'],
    'BSc Metal Product Design Technology': ['Physics', 'Mathematics', ['Technical Drawing', 'Metalwork']],
    'BSc Textile Design and Technology': ['General Knowledge in Art', ['Textiles', 'Graphic Design']],
    'BSc Fashion Design': ['General Knowledge in Art', ['Textiles', 'Clothing and Textiles']],
    'BSc Ceramics Technology': ['General Knowledge in Art', ['Ceramics', 'Sculpture']],
    'BEd Junior High School Education': ['Any three electives'],
    'BSc Aerospace Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BSc Agricultural Engineering': ['Physics', 'Mathematics', ['Chemistry', 'General Agriculture']],
    'BSc Automobile Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing', 'Auto Mechanics']],
    'BSc Biomedical Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Biology']],
    'BSc Chemical Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Civil Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Computer Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BSc Electrical/Electronic Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BSc Geological Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Geomatic Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Geography']],
    'BSc Industrial Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Marine Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing']],
    'BSc Materials Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Mechanical Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing']],
    'BSc Metallurgical Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Petrochemical Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Petroleum Engineering': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Telecommunication Engineering': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BDS Bachelor of Dental Surgery (Fee-Paying Only)': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'DVM Doctor of Veterinary Medicine': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Disability and Rehabilitation Studies': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BHM Bachelor of Herbal Medicine': ['Biology', 'Chemistry', ['Physics', 'General Agriculture']],
    'BSc Human Biology (Medicine)': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Medical Laboratory Sciences': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Medical Imaging': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Midwifery': ['Biology', 'Chemistry', ['Physics', 'Mathematics', 'General Agriculture']],
    'BSc Nursing': ['Biology', 'Chemistry', ['Physics', 'Mathematics', 'General Agriculture']],
    'BSc Physiotherapy and Sports Science': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'PharmD Doctor of Pharmacy': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BA Akan Language and Culture': ['Akan', ['Literature in English', 'History', 'Government']],
    'BA Economics': ['Economics', 'Mathematics', ['Geography', 'Government']],
    'BA English': ['Literature in English', ['History', 'Government']],
    'BA French and Francophone Studies': ['French', ['Literature in English', 'History']],
    'BA Geography and Rural Development': ['Geography', ['Economics', 'Government', 'History']],
    'BA History': ['History', ['Government', 'Literature in English']],
    'BA Linguistics': ['English Literature', ['French', 'Akan', 'Government']],
    'BA Media and Communication Studies': ['English Literature', ['Government', 'History']],
    'BA Political Studies': ['Government', ['History', 'Economics']],
    'BA Religion and Human Development': ['Christian Religious Studies', ['History', 'Government']],
    'BA Sociology': ['Government', ['History', 'Economics']],
    'BA Social Work': ['Government', ['History', 'Economics']],
    'BSc Business Administration (Human Resource Management/Management)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BSc Business Administration (Marketing/International Business)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BSc Business Administration (Accounting/Banking and Finance)': ['Accounting', 'Business Management', ['Economics', 'Mathematics']],
    'BSc Business Administration (Logistics and Supply Chain Management/Business Information Technology)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BSc Hospitality and Tourism Management': ['Economics', 'Geography', ['Business Management', 'Government']],
    'LLB': ['English Literature', ['History', 'Government']],
    'BSc Biochemistry': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Food Science and Technology': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Biological Sciences': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Environmental Sciences': ['Biology', 'Chemistry', ['Physics', 'Geography']],
    'BSc Chemistry': ['Chemistry', 'Physics', 'Mathematics'],
    'BSc Computer Science': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BSc Mathematics': ['Mathematics', ['Physics', 'Chemistry']],
    'BSc Actuarial Science': ['Mathematics', ['Economics', 'Accounting']],
    'BSc Statistics': ['Mathematics', ['Physics', 'Economics']],
    'BSc Physics': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Meteorology and Climate Science': ['Physics', 'Mathematics', ['Chemistry', 'Geography']],
    'Doctor of Optometry': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Civil Engineering (Obuasi Campus)': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Electrical/Electronic Engineering (Obuasi Campus)': ['Physics', 'Mathematics', ['Chemistry', 'Applied Electricity', 'Electronics']],
    'BSc Geological Engineering (Obuasi Campus)': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Geomatic Engineering (Obuasi Campus)': ['Physics', 'Mathematics', ['Chemistry', 'Geography']],
    'BSc Materials Engineering (Obuasi Campus)': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Mechanical Engineering (Obuasi Campus)': ['Physics', 'Mathematics', ['Chemistry', 'Technical Drawing']],
    'BSc Metallurgical Engineering (Obuasi Campus)': ['Physics', 'Mathematics', 'Chemistry'],
    'BSc Medical Laboratory Sciences (Obuasi Campus)': ['Biology', 'Chemistry', ['Physics', 'Mathematics']],
    'BSc Midwifery (Obuasi Campus)': ['Biology', 'Chemistry', ['Physics', 'Mathematics', 'General Agriculture']],
    'BSc Nursing (Obuasi Campus)': ['Biology', 'Chemistry', ['Physics', 'Mathematics', 'General Agriculture']],
    'BBA (HRM/Management) (Obuasi Campus)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BBA (Marketing/International Business) (Obuasi Campus)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BBA (Accounting/Banking and Finance) (Obuasi Campus)': ['Accounting', 'Business Management', ['Economics', 'Mathematics']],
    'BBA (Logistics & Supply Chain Management/Business Information Technology) (Obuasi Campus)': ['Economics', 'Business Management', ['Accounting', 'Mathematics']],
    'BSc Environmental Sciences (Obuasi Campus)': ['Biology', 'Chemistry', ['Physics', 'Geography']]
  };
  
  const programToCollege = {
    'BSc Agriculture': 'College of Agriculture and Natural Resources',
    'BSc Agricultural Biotechnology': 'College of Agriculture and Natural Resources',
    'BSc Agribusiness Management': 'College of Agriculture and Natural Resources',
    'BSc Landscape Design and Management': 'College of Agriculture and Natural Resources',
    'BSc Natural Resources Management': 'College of Agriculture and Natural Resources',
    'BSc Forest Resources Technology': 'College of Agriculture and Natural Resources',
    'BSc Aquaculture and Water Resources Management': 'College of Agriculture and Natural Resources',
    'BSc Packaging Technology': 'College of Agriculture and Natural Resources',
    'BSc Architecture': 'College of Art and Built Environment',
    'BSc Construction Technology and Management': 'College of Art and Built Environment',
    'BSc Quantity Surveying and Construction Economics': 'College of Art and Built Environment',
    'BSc Development Planning': 'College of Art and Built Environment',
    'BSc Human Settlement Planning': 'College of Art and Built Environment',
    'BSc Land Economy': 'College of Art and Built Environment',
    'BSc Real Estate': 'College of Art and Built Environment',
    'BFA Fine Art and Curatorial Practice': 'College of Art and Built Environment',
    'BA Communication Design': 'College of Art and Built Environment',
    'BA Integrated Rural Art and Industry': 'College of Art and Built Environment',
    'BA Publishing Studies': 'College of Art and Built Environment',
    'BSc Metal Product Design Technology': 'College of Art and Built Environment',
    'BSc Textile Design and Technology': 'College of Art and Built Environment',
    'BSc Fashion Design': 'College of Art and Built Environment',
    'BSc Ceramics Technology': 'College of Art and Built Environment',
    'BEd Junior High School Education': 'College of Art and Built Environment',
    'BSc Aerospace Engineering': 'College of Engineering',
    'BSc Agricultural Engineering': 'College of Engineering',
    'BSc Automobile Engineering': 'College of Engineering',
    'BSc Biomedical Engineering': 'College of Engineering',
    'BSc Chemical Engineering': 'College of Engineering',
    'BSc Civil Engineering': 'College of Engineering',
    'BSc Computer Engineering': 'College of Engineering',
    'BSc Electrical/Electronic Engineering': 'College of Engineering',
    'BSc Geological Engineering': 'College of Engineering',
    'BSc Geomatic Engineering': 'College of Engineering',
    'BSc Industrial Engineering': 'College of Engineering',
    'BSc Marine Engineering': 'College of Engineering',
    'BSc Materials Engineering': 'College of Engineering',
    'BSc Mechanical Engineering': 'College of Engineering',
    'BSc Metallurgical Engineering': 'College of Engineering',
    'BSc Petrochemical Engineering': 'College of Engineering',
    'BSc Petroleum Engineering': 'College of Engineering',
    'BSc Telecommunication Engineering': 'College of Engineering',
    'BDS Bachelor of Dental Surgery (Fee-Paying Only)': 'College of Health Sciences',
    'DVM Doctor of Veterinary Medicine': 'College of Health Sciences',
    'BSc Disability and Rehabilitation Studies': 'College of Health Sciences',
    'BHM Bachelor of Herbal Medicine': 'College of Health Sciences',
    'BSc Human Biology (Medicine)': 'College of Health Sciences',
    'BSc Medical Laboratory Sciences': 'College of Health Sciences',
    'BSc Medical Imaging': 'College of Health Sciences',
    'BSc Midwifery': 'College of Health Sciences',
    'BSc Nursing': 'College of Health Sciences',
    'BSc Physiotherapy and Sports Science': 'College of Health Sciences',
    'PharmD Doctor of Pharmacy': 'College of Health Sciences',
    'BA Akan Language and Culture': 'College of Humanities and Social Sciences',
    'BA Economics': 'College of Humanities and Social Sciences',
    'BA English': 'College of Humanities and Social Sciences',
    'BA French and Francophone Studies': 'College of Humanities and Social Sciences',
    'BA Geography and Rural Development': 'College of Humanities and Social Sciences',
    'BA History': 'College of Humanities and Social Sciences',
    'BA Linguistics': 'College of Humanities and Social Sciences',
    'BA Media and Communication Studies': 'College of Humanities and Social Sciences',
    'BA Political Studies': 'College of Humanities and Social Sciences',
    'BA Religion and Human Development': 'College of Humanities and Social Sciences',
    'BA Sociology': 'College of Humanities and Social Sciences',
    'BA Social Work': 'College of Humanities and Social Sciences',
    'BSc Business Administration (Human Resource Management/Management)': 'College of Humanities and Social Sciences',
    'BSc Business Administration (Marketing/International Business)': 'College of Humanities and Social Sciences',
    'BSc Business Administration (Accounting/Banking and Finance)': 'College of Humanities and Social Sciences',
    'BSc Business Administration (Logistics and Supply Chain Management/Business Information Technology)': 'College of Humanities and Social Sciences',
    'BSc Hospitality and Tourism Management': 'College of Humanities and Social Sciences',
    'LLB': 'College of Humanities and Social Sciences',
    'BSc Biochemistry': 'College of Science',
    'BSc Food Science and Technology': 'College of Science',
    'BSc Biological Sciences': 'College of Science',
    'BSc Environmental Sciences': 'College of Science',
    'BSc Chemistry': 'College of Science',
    'BSc Computer Science': 'College of Science',
    'BSc Mathematics': 'College of Science',
    'BSc Actuarial Science': 'College of Science',
    'BSc Statistics': 'College of Science',
    'BSc Physics': 'College of Science',
    'BSc Meteorology and Climate Science': 'College of Science',
    'Doctor of Optometry': 'College of Science',
    'BSc Civil Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Electrical/Electronic Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Geological Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Geomatic Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Materials Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Mechanical Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Metallurgical Engineering (Obuasi Campus)': 'Obuasi Campus',
    'BSc Medical Laboratory Sciences (Obuasi Campus)': 'Obuasi Campus',
    'BSc Midwifery (Obuasi Campus)': 'Obuasi Campus',
    'BSc Nursing (Obuasi Campus)': 'Obuasi Campus',
    'BBA (HRM/Management) (Obuasi Campus)': 'Obuasi Campus',
    'BBA (Marketing/International Business) (Obuasi Campus)': 'Obuasi Campus',
    'BBA (Accounting/Banking and Finance) (Obuasi Campus)': 'Obuasi Campus',
    'BBA (Logistics & Supply Chain Management/Business Information Technology) (Obuasi Campus)': 'Obuasi Campus',
    'BSc Environmental Sciences (Obuasi Campus)': 'Obuasi Campus'
  };
  
  const pdfData = {
    programs: [],
    deadlines: {
      regular: '31st December, 2024',
      extension: '28th February, 2025'
    }
  };
  
  module.exports = {
    validPrograms,
    cutOffAggregates,
    collegeFees,
    electiveRequirements,
    programToCollege,
    pdfData
  };